name: slickbill
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.18.0
  badges: ^3.1.2
  json_annotation: ^4.8.1
  flutter_hooks: ^0.20.5
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.6.0
  persistent_bottom_nav_bar: ^5.0.2
  flutter_local_notifications: ^17.0.0
  syncfusion_flutter_datepicker: ^30.2.7
  syncfusion_flutter_pdf: ^30.2.7
  syncfusion_flutter_pdfviewer: ^30.2.7
  liquid_pull_to_refresh: ^3.0.1
  supabase_flutter: ^2.5.6
  file_picker: ^8.1.0
  http: ^1.2.1
  http_parser: ^4.0.2
  html_unescape: ^2.0.0
  modal_bottom_sheet: ^3.0.0
  flutter_typeahead: ^5.2.0
  image_picker: ^1.2.0
  image_picker_for_web: ^3.0.4
  nfc_manager: ^3.4.0
  flutter_nfc_hce: ^0.1.8
  pulsator: ^1.0.0
  qr_flutter: ^4.1.0
  path_provider: ^2.1.1
  mobile_scanner: ^7.0.1
  loader_overlay: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - media/temporary_logo.png
    - media/temporary_logo_text.png
    - media/logo blue.webp

dependency_overrides:
  web: ^0.5.1
  image_picker_platform_interface: ^2.11.0
  path_provider_android: ^2.2.1  # Add this to force newer version
  path_provider_platform_interface: ^2.1.1 
  url_launcher_android: ^6.3.0