// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    final options = currentPlatformOrNull;
    if (options != null) {
      return options;
    }

    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static FirebaseOptions? get currentPlatformOrNull {
    if (kIsWeb) {
      return null;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return null;
      case TargetPlatform.windows:
        return null;
      case TargetPlatform.linux:
        return null;
      default:
        return null;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUk_Hr6sYUyijGxSiQhB8w8l-CibHYHVg',
    appId: '1:285202567016:android:95298770f25574fa0d10dd',
    messagingSenderId: '285202567016',
    projectId: 'slickbills',
    storageBucket: 'slickbills.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeHiUglOqTczDaJJT6f9_z9VOIjHmaaWo',
    appId: '1:285202567016:ios:990a747562e54c820d10dd',
    messagingSenderId: '285202567016',
    projectId: 'slickbills',
    storageBucket: 'slickbills.firebasestorage.app',
    iosBundleId: 'com.denniskumar.slickbill',
  );
}
